### ISSUE TITLE
Use upstream yolo3 source as git submodule

### ISSUE THREAD

**Issue by bleggett** [tmobile/node-red-contrib-yolo-object-detection#4]
Currently this repo uses a modified version of https://github.com/qqwweee/keras-yolo3 with tweaked imports - this should be replaced with a clean git submodule of the upstream source tree

**Comment by jbondpk** [comment]
@bleggett - Created initial yolo3-keras here https://github.com/jbondpk/keras-yolo3 taking the codebase from the current inventory and yolo object detection as a starting point.  Please review and fork to T-Mobile and then can then repoint these repos to it as submodules.  Let me know if you have any questions.  Thanks.

**Comment by jbondpk** [comment]
@bleggett - Closing this issue as related to prior merge request that was merged.
